# Autogenerated by devscripts/update-version.py

__version__ = '2023.12.05.155107'

RELEASE_GIT_HEAD = '5d22680e90ca4fc7d9d378152f9db69ccc425ddf'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'najloa/yt-dlp'

ORIGIN = 'najloa/yt-dlp'

_pkg_version = '2023.12.05.155107'
